cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/versions'

brew 'dlite'
brew 'docker-compose'
brew 'docker'
brew 'ffmpeg'
brew 'gifsicle'
brew 'git'
brew 'go'
brew 'graphviz'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'maven32'
brew 'node'
brew 'python'
brew 'pyenv'
brew 'rbenv'
brew 'redis'
brew 'shellcheck'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'unrar'
brew 'vim'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

# gnu stuff
brew 'coreutils'
brew 'findutils'
brew 'gnu-tar'
brew 'gnu-sed'
brew 'gawk'
brew 'gnutls'
brew 'gnu-indent'
brew 'gnu-getopt'

# casks
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'

cask 'android-file-transfer'
cask 'appcleaner'
cask 'atom'
cask 'beamer'
cask 'caffeine'
cask 'diffmerge'
cask 'disk-inventory-x'
cask 'dropbox'
cask 'font-hack'
cask 'google-chrome'
cask 'iterm2-beta'
cask 'postgres'
cask 'slack'
cask 'slate'
cask 'spotify'
cask 'telegram'
cask 'the-unarchiver'
cask 'transmission'
cask 'viscosity'
cask 'vlc'

# https://github.com/sindresorhus/quick-look-plugins
cask 'betterzipql'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlprettypatch'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'suspicious-package'
cask 'webpquicklook'
