#!/bin/bash
set -e

# shcheck files
curl -sL https://git.io/shcheck | bash -x -f -s -- \
	--ignore 'script/test' \
	--ignore 'vim/vim.symlink/**/*' \
	--ignore 'zsh/config.zsh' \
	--ignore 'zsh/completion.zsh' \
	--ignore 'zsh/prompt.zsh' \
	--ignore 'zsh/fpath.zsh' \
	--ignore 'atom.symlink/packages/**/*' \
	--ignore 'vim/vim.symlink/bundle/**/*' \
	--ignore 'docker/completion.zsh'
