#!/usr/bin/env bash
#
# Install dotfiles.
set -eo pipefail

if [ -d ~/.dotfiles ]; then
  echo "A ~/.dotfiles folder already exists, backup it and run this again!"
  exit 1
fi

if test "$(which apt-get)"; then
  alias install_pkg="sudo apt-get install"
fi

if test ! "$(which git)"; then
  install_pkg git
fi
if test ! "$(which zsh)"; then
  install_pkg zsh
fi

git clone --recursive https://github.com/caarlos0/dotfiles ~/.dotfiles
zsh ~/.dotfiles/script/bootstrap
sudo chsh -s /bin/zsh
echo "All done! Please, restart your terminal session!"
