#!/usr/bin/env bash
#
# Run all dotfiles installers.
set -e

cd "$(dirname "$0")"/..

if test "$(uname)" = "Darwin"; then
  # Run Homebrew through the Brewfile
  echo "› brew bundle"
  brew bundle
fi

# find the installers and run them iteratively
find . -name install.sh | grep -v "build" | while read -r installer; do
  echo "› ${installer}..."
  sh -c "$installer"
done
