#!/bin/zsh
set -e

# Lint files
./build/build.sh

# link to ~ and cd to it
cd ..
cp -rf dotfiles ~/.dotfiles
cd ~/.dotfiles

# setup git credentials
git config --global user.name "dotfiles demo"
git config --global user.email "dotfiles@demo.com"

# bootstrap the mighty
./script/bootstrap --override-all

# load zshrc and check if antibody is working
source ~/.zshrc
antibody list
git config --global --list
